name: Substituir Logo do Bizagi

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Baixar código do repositório
        uses: actions/checkout@v4

      - name: Substituir logos do Bizagi pelo personalizado
        run: |
          ls -la custom-assets libs/img   # ajuda a depurar caminhos
          cp custom-assets/Logo_IFC_horizontal.png libs/img/biz-ex-logo.png
          cp custom-assets/Logo_IFC_horizontal_2x.png libs/img/biz-ex-logo-2x.png
          touch .nojekyll

      - name: Publicar no GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: .
          branch: gh-pages